const {test,after}=require('node:test');const assert=require('node:assert/strict');const {spawn}=require('node:child_process');const path=require('node:path'),crypto=require('node:crypto');
const {useIsolatedDb,dropIsolatedDb}=require('./helpers/db');const file=useIsolatedDb(`promo-processes-${process.pid}`);process.env.PROMO_CODE_ENCRYPTION_KEY=crypto.randomBytes(32).toString('base64');const db=require('../src/config/prisma').basePrisma;after(async()=>{await db.$disconnect();dropIsolatedDb(file)});
const source=`const db=require('./src/config/prisma').basePrisma;const s=require('./src/services/promotions');process.once('message',async m=>{try{process.send({status:200,data:await s[m.method](m.input,m.actor)})}catch(e){process.send({status:e.status||500})}finally{await db.$disconnect();process.disconnect()}});process.send({ready:true});`;
function worker(t){const child=spawn(process.execPath,['-e',source],{cwd:path.join(__dirname,'..'),env:process.env,stdio:['ignore','ignore','ignore','ipc']});let resolve,reply;const ready=new Promise(r=>{resolve=r});const done=new Promise((r,j)=>{child.on('message',m=>{if(m.ready)resolve();else reply=m});child.once('error',j);child.once('exit',code=>code===0&&reply?r(reply):j(new Error('isolated worker failed')))});t.after(()=>{if(child.exitCode==null)child.kill()});return {ready,done,start:message=>child.send(message)}}
test('发码与跨店领取跨进程竞争/重启恢复不重复；失败事务不消费码',async t=>{
 const admin=await db.platformAdmin.create({data:{username:'multi-platform',passwordHash:'unused',displayName:'test'}});const input={requestId:crypto.randomUUID(),count:1,label:'multi',redeemExpiresAt:null};
 const generators=[worker(t),worker(t)];await Promise.all(generators.map(w=>w.ready));generators.forEach(w=>w.start({method:'createBatch',input,actor:admin}));const generated=await Promise.all(generators.map(w=>w.done));assert(generated.every(r=>r.status===200));assert.deepEqual(generated[0].data.codes,generated[1].data.codes);assert.equal(await db.promoBatch.count(),1);const code=generated[0].data.codes[0];
 const actors=[];for(const suffix of ['a','b']){const store=await db.store.create({data:{name:suffix}});const u=await db.user.create({data:{storeId:store.id,username:'multi-'+suffix,passwordHash:'unused',realName:suffix,role:'admin'}});actors.push({userId:u.id,storeId:store.id,role:'admin',sessionVersion:0})}
 const claimers=[worker(t),worker(t)];await Promise.all(claimers.map(w=>w.ready));claimers.forEach((w,i)=>w.start({method:'redeem',input:{code:code.code},actor:actors[i]}));const claimed=await Promise.all(claimers.map(w=>w.done));assert.deepEqual(claimed.map(r=>r.status).sort(),[200,409]);const winner=actors[claimed.findIndex(r=>r.status===200)];
 const restart=worker(t);await restart.ready;restart.start({method:'redeem',input:{code:code.code},actor:winner});const recovered=await restart.done;assert.equal(recovered.status,200);assert.equal(recovered.data.replayed,true);assert.equal(await db.entitlement.count({where:{source:'promotion'}}),1);assert.equal(await db.platformAudit.count({where:{action:'promo.redeem'}}),1);
 const service=require('../src/services/promotions');const next=(await service.createBatch({...input,requestId:crypto.randomUUID()},admin)).codes[0];await db.$executeRawUnsafe(`CREATE TRIGGER fail_promo BEFORE INSERT ON Entitlement WHEN NEW.source='promotion' BEGIN SELECT RAISE(ABORT,'isolated rollback'); END`);
 await assert.rejects(()=>service.redeem({code:next.code},winner));assert.equal((await db.promoCode.findUnique({where:{id:next.id}})).state,'unused');assert.equal(await db.entitlement.count(),1);await db.$executeRawUnsafe('DROP TRIGGER fail_promo');assert.equal((await service.redeem({code:next.code},winner)).replayed,false);
});
