const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');
const {useIsolatedDb,dropIsolatedDb}=require('./helpers/db');const file=useIsolatedDb(`promo-${process.pid}`);
process.env.JWT_SECRET=crypto.randomBytes(32).toString('hex');process.env.PLATFORM_JWT_SECRET=crypto.randomBytes(32).toString('hex');process.env.PROMO_CODE_ENCRYPTION_KEY=crypto.randomBytes(32).toString('base64');
const prisma=require('../src/config/prisma'),express=require('express'),ctl=require('../src/controllers/promotions');const {issueJwt}=require('../src/services/session');const {auth}=require('../src/middlewares/auth');const {wrap}=require('../src/utils/response');
let server,base,admin,owner,other,staff,ownerToken,otherToken,staffToken;
before(async()=>{admin=await prisma.basePrisma.platformAdmin.create({data:{username:'platform-promo',passwordHash:'unusable',displayName:'合成平台'}});for(const name of ['A','B']){const store=await prisma.basePrisma.store.create({data:{name:'促销测试'+name}});const u=await prisma.basePrisma.user.create({data:{storeId:store.id,username:'promo-'+name,passwordHash:'unusable',realName:name,role:'admin'}});if(name==='A')owner=u;else other=u}staff=await prisma.basePrisma.user.create({data:{storeId:owner.storeId,username:'promo-staff',passwordHash:'unusable',realName:'staff',role:'staff'}});ownerToken=issueJwt(owner);otherToken=issueJwt(other);staffToken=issueJwt(staff);const app=express();app.use(express.json());const platform=(req,_res,next)=>{req.platformAdmin=admin;next()};app.post('/platform/batches',platform,wrap(ctl.createBatch));app.get('/platform/codes',platform,wrap(ctl.listCodes));app.post('/platform/codes/:id/disable',platform,wrap(ctl.disable));app.post('/platform/codes/:id/revoke',platform,wrap(ctl.revoke));app.post('/redeem',auth,wrap(ctl.redeem));app.use('/api/v1',require('../src/routes'));app.use(require('../src/middlewares/errorHandler'));server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base=`http://127.0.0.1:${server.address().port}`});
after(async()=>{if(server)await new Promise(r=>server.close(r));await prisma.$disconnect();dropIsolatedDb(file)});
async function call(path,body,token){const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:body===undefined?undefined:JSON.stringify(body)});return {status:r.status,body:await r.json()}}
const input=()=>({requestId:crypto.randomUUID(),label:'合成免费体验',count:2,redeemExpiresAt:null});
test('生成原请求重试同码/异内容冲突；普通列表和审计不泄露码',async()=>{const body=input();const a=await call('/platform/batches',body);assert.equal(a.status,200);const b=await call('/platform/batches',body);assert.deepEqual(b.body.data.codes,a.body.data.codes);assert.equal(b.body.data.replayed,true);assert.equal((await call('/platform/batches',{...body,label:'改内容'})).status,409);const list=await call('/platform/codes');const rows=await prisma.basePrisma.promoCode.findMany(),batches=await prisma.basePrisma.promoBatch.findMany(),audit=await prisma.basePrisma.platformAudit.findMany();for(const c of a.body.data.codes){assert(!JSON.stringify({list,rows,batches,audit}).includes(c.code));assert.match(c.code,/^ZC-[A-Z2-9]{4}(?:-[A-Z2-9]{4}){3}$/)}});
test('仅店主能兑换，同店并发重试只一权益/另一店拒绝，员工不升级',async()=>{const c=(await call('/platform/batches',input())).body.data.codes[0];assert.equal((await call('/redeem',{code:c.code},staffToken)).status,403);const [a,b]=await Promise.all([call('/redeem',{code:c.code},ownerToken),call('/redeem',{code:c.code},ownerToken)]);assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(a.body.data.grant.id,b.body.data.grant.id);assert.equal(a.body.data.entitlement.expiresAt,null);assert.equal((await call('/redeem',{code:c.code},otherToken)).status,409);assert.equal(await prisma.basePrisma.entitlement.count({where:{source:'promotion',externalId:c.id}}),1);assert.equal((await prisma.basePrisma.user.findUnique({where:{id:staff.id}})).role,'staff')});
test('跨店并发仅一赢家，领取与权益一致',async()=>{const c=(await call('/platform/batches',input())).body.data.codes[0];const results=await Promise.all([call('/redeem',{code:c.code},ownerToken),call('/redeem',{code:c.code},otherToken)]);assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);const code=await prisma.basePrisma.promoCode.findUnique({where:{id:c.id}});const grants=await prisma.basePrisma.entitlement.findMany({where:{source:'promotion',externalId:c.id}});assert.equal(grants.length,1);assert.equal(grants[0].storeId,code.storeId)});
test('停用未领码不可用；撤销已领体验不触碰Apple，重试不复活',async()=>{const codes=(await call('/platform/batches',input())).body.data.codes;assert.equal((await call(`/platform/codes/${codes[0].id}/disable`,{reason:'停止发放'})).status,200);assert.equal((await call('/redeem',{code:codes[0].code},ownerToken)).status,410);await prisma.basePrisma.entitlement.create({data:{storeId:other.storeId,plan:'pro',source:'apple',externalId:'synthetic-not-receipt',appleEnvironment:'Sandbox',expiresAt:new Date(Date.now()+86400000)}});await call('/redeem',{code:codes[1].code},otherToken);assert.equal((await call(`/platform/codes/${codes[1].id}/revoke`,{reason:'收回测试'})).status,200);assert.equal((await call(`/platform/codes/${codes[1].id}/revoke`,{reason:'重复收回'})).status,200);assert.equal((await call('/redeem',{code:codes[1].code},otherToken)).status,410);assert.equal((await prisma.basePrisma.entitlement.findUnique({where:{source_externalId:{source:'apple',externalId:'synthetic-not-receipt'}}})).status,'active')});
test('过期/禁用身份/错误格式拒绝，不新建身份店铺',async()=>{const counts=[await prisma.basePrisma.user.count(),await prisma.basePrisma.store.count()];const c=(await call('/platform/batches',input())).body.data.codes[0];await prisma.basePrisma.promoCode.update({where:{id:c.id},data:{redeemExpiresAt:new Date(0)}});assert.equal((await call('/redeem',{code:c.code},ownerToken)).status,410);assert.equal((await call('/redeem',{code:'bad'},ownerToken)).status,400);await prisma.basePrisma.user.update({where:{id:owner.id},data:{status:0}});assert.equal((await call('/redeem',{code:c.code},ownerToken)).status,401);assert.deepEqual([await prisma.basePrisma.user.count(),await prisma.basePrisma.store.count()],counts)});

test('实际统一路由平台认证隔离，生产字段形状和no-store',async()=>{
 const bcrypt=require('bcryptjs');const password='Synthetic-Platform-Pass-2026';await prisma.basePrisma.platformAdmin.update({where:{id:admin.id},data:{passwordHash:await bcrypt.hash(password,10)}});
 const login=await call('/api/v1/platform/auth/login',{username:admin.username,password});assert.equal(login.status,200);const token=login.body.data.token;
 assert.equal((await call('/api/v1/platform/promo-codes',undefined,otherToken)).status,401);assert.equal((await call('/api/v1/auth/profile',undefined,token)).status,401);
 const created=await call('/api/v1/platform/promo-batches',input(),token);assert.equal(created.status,200);assert.equal((await call('/api/v1/platform/promo-codes',undefined,token)).status,200);
 const denied=await fetch(base+'/api/v1/platform/promo-codes');assert.equal(denied.status,401);assert.equal(denied.headers.get('cache-control'),'no-store');
});
